### ISSUE TITLE
vctl pull mono

### ISSUE THREAD

**Issue by seanjwong** [VMwareFusion/vctl-docs#29]
Any hints ?

Seans-Mac-Pro:~ Sean__Wong$ vctl system start
Preparing storage...
Container storage has been prepared successfully under /Users/Sean__Wong/.vctl/storage
Preparing container network, you may be prompted to input password for administrative operations...
Password:
Container network has been prepared successfully using vmnet: vmnet9
Launching container runtime...
Container runtime has been started.
Seans-Mac-Pro:~ Sean__Wong$ vctl pull mono
INFO Pulling from index.docker.io/library/mono:latest 
───                                                                                ──────   ────────                     
REF                                                                                STATUS   PROGRESS                     
───                                                                                ──────   ────────                     
index-sha256:e6e25d424d464706fdaeb058dae2a9d7690ec2773168d9fd2a1aa689b169be4b      Done     100% (1431/1431)             
manifest-sha256:18384bd31a4d16c228a893267a7943b7aea1f263f75ed23cd9a139e5cd844b1b   Done     100% (1164/1164)             
layer-sha256:68ccfe204fbb0bc2d09a50ebeab14fc143f44a9a8fbf474784b0bb3b83f805a6      Done     100% (130288603/130288603)   
layer-sha256:bf59529304463f62efa7179fa1a32718a611528cc4ce9f30c0d1bbc6724ec3fb      Done     100% (27092121/27092121)     
config-sha256:ecda9bfba7e60c3f947af76aa7f409fcb0ba0016af425a2c9469882c4cf09f2c     Done     100% (3350/3350)             
layer-sha256:1b84988e9412eb7cdedbd0cd734d319d6e7694cf8b8c6b50383a7d9d0bd65408      Done     100% (67092668/67092668)     
layer-sha256:f9430cf70b26259617fdf6dea56de0841e6a2d05e7996d61d9b457d837624f2c      Done     100% (255895/255895)         
INFO Unpacking mono:latest...                     
ERROR failed to prepare extraction snapshot "extract-865500000-ZU8W sha256:d0f104dc0a1f9c744b65b23b3fd4d4d3236b4656e67f776fe13f8ad8423b955c": failed to create temp dmg: exit status 1: unknown

**Comment by mikeroySoft** [comment]
Might be that the vctl version with Fusion 11.5.x currently has a bug, I am on the fusion 12 version and it's working no probs.

What do your containerd logs say?  (~/.vctl/containerd.log)

mike@OctoBook  ~  vctl pull mono
INFO Pulling from index.docker.io/library/mono:latest
───                                                                                ──────   ────────
REF                                                                                STATUS   PROGRESS
───                                                                                ──────   ────────
index-sha256:e6e25d424d464706fdaeb058dae2a9d7690ec2773168d9fd2a1aa689b169be4b      Done     100% (1431/1431)
manifest-sha256:18384bd31a4d16c228a893267a7943b7aea1f263f75ed23cd9a139e5cd844b1b   Done     100% (1164/1164)
layer-sha256:68ccfe204fbb0bc2d09a50ebeab14fc143f44a9a8fbf474784b0bb3b83f805a6      Done     100% (130288603/130288603)
layer-sha256:bf59529304463f62efa7179fa1a32718a611528cc4ce9f30c0d1bbc6724ec3fb      Done     100% (27092121/27092121)
layer-sha256:f9430cf70b26259617fdf6dea56de0841e6a2d05e7996d61d9b457d837624f2c      Done     100% (255895/255895)
config-sha256:ecda9bfba7e60c3f947af76aa7f409fcb0ba0016af425a2c9469882c4cf09f2c     Done     100% (3350/3350)
layer-sha256:1b84988e9412eb7cdedbd0cd734d319d6e7694cf8b8c6b50383a7d9d0bd65408      Done     100% (67092668/67092668)
INFO Unpacking mono:latest...
INFO done
 mike@OctoBook  ~  vctl run -n myMono -t -d mono:latest
INFO container myMono started and detached from current session
 mike@OctoBook  ~  vctl ps
────     ─────         ───────   ──               ─────   ──────    ─────────────
NAME     IMAGE         COMMAND   IP               PORTS   STATUS    CREATION TIME
────     ─────         ───────   ──               ─────   ──────    ─────────────
myMono   mono:latest   bash      172.16.139.153   n/a     running   2020-08-31T17:11:01-07:00
 mike@OctoBook  ~ 

**Comment by seanjwong** [comment]
@mikeroySoft  Ireally appreciate your reply, I gave up and went back to Docker. I'll look at it again ITF.
